# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 23:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161126_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['slug']},
        ),
        migrations.AlterField(
            model_name='certificat',
            name='certificat_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 26, 23, 9, 35, 80396, tzinfo=utc), verbose_name='Date'),
        ),
    ]
